name: Deploy Vite project to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# 👇 AGREGAR ESTO - indica que tu proyecto está en myshop/
defaults:
  run:
    working-directory: myshop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          # 👇 AGREGAR esto también
          cache-dependency-path: myshop/package-lock.json

      - name: Install dependencies
        run: npm ci
        # 👇 El working-directory aplica automáticamente aquí

      - name: Build Vite project
        run: npm run build

      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 👇 AGREGAR myshop/ aquí también
          path: myshop/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
